[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49" }
clap_derive = "4.5.49"
directories = "6.0.0"
dotenv = "0.15.0"
futures = "0.3.31"
llm = { path = "../llm" }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
