[workspace]
resolver = "3"
members = ["commands", "config", "noema-core", "noema-core/llm", "noema-audio", "noema-ext", "noema-desktop/src-tauri", "noema-mcp-gdocs", "noema-backend"]
default-members = ["noema-desktop/src-tauri"]
