[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10"
base64 = "0.22"
dirs = "6.0"
dotenv = "0.15.0"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
toml = "0.8"
whoami = "1.6"
